[project]
name = "peft-geofm"
version = "0.0.1"
requires-python = ">=3.10,<3.13"

dependencies = [
  "matplotlib",
  "ipykernel",
  "pandas",
  "seaborn",
  "terratorch[peft]",
  "albumentations>=1.4.6",
  "numpy",
  "torch<2.6.0",# for deformable attn
  "pyproj",
  "xarray",
  "tqdm",
]
