seed_everything: 0
trainer:
  accelerator: auto
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        patience: 15

  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 1
  enable_checkpointing: true
  default_root_dir: <path>

data: ../../../datamodules/m_sa_crop_type/no_metadata_decur_bands.yaml

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: ssl4eos12_resnet50_sentinel2_all_decur
      backbone_pretrained: true
      backbone_model_bands:
        [
          "COASTAL_AEROSOL",
          "BLUE",
          "GREEN",
          "RED",
          "RED_EDGE_1",
          "RED_EDGE_2",
          "RED_EDGE_3",
          "NIR_BROAD",
          "NIR_NARROW",
          "WATER_VAPOR",
          "SWIR_1",
          "SWIR_2",
        ]
      backbone_out_indices: [1, 2, 3, 4]
      decoder: LinearDecoder
      decoder_upsampling_size: 32
      rescale: false
      num_classes: 10
    loss: ce
    ignore_index: -1
    freeze_backbone: true
    optimizer: AdamW
    lr: 0.0009670420395319958
    scheduler: ReduceLROnPlateau
    scheduler_hparams:
      patience: 4
      factor: 0.5
    plot_on_val: False
