seed_everything: 0
trainer:
  accelerator: auto
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        patience: 15

  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 1
  enable_checkpointing: true
  default_root_dir: <path>

data: ../../../datamodules/reBEN_7k/no_metadata_prithvi_bands.yaml

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: prithvi_eo_v1_100
      backbone_pretrained: true
      backbone_bands: ["BLUE", "GREEN", "RED", "NIR_NARROW", "SWIR_1", "SWIR_2"]
      necks:
        - name: SelectIndices
          indices: [-1]
        - name: ReshapeTokensToImage
      decoder: LinearDecoder
      decoder_upsampling_size: 16
      rescale: false
      num_classes: 19
    loss: ce
    ignore_index: -1
    freeze_backbone: true
    optimizer: AdamW
    lr: 0.0007576527195766431
    scheduler: ReduceLROnPlateau
    scheduler_hparams:
      patience: 4
      factor: 0.5
    class_names:
      [
        "Agro-forestry areas",
        "Arable land",
        "Beaches, dunes, sands",
        "Broad-leaved forest",
        "Coastal wetlands",
        "Complex cultivation patterns",
        "Coniferous forest",
        "Industrial or commercial units",
        "Inland waters",
        "Inland wetlands",
        "Land principally occupied by agriculture, with significant areas of natural vegetation",
        "Marine waters",
        "Mixed forest",
        "Moors, heathland and sclerophyllous vegetation",
        "Natural grassland and sparsely vegetated areas",
        "Pastures",
        "Permanent crops",
        "Transitional woodland, shrub",
        "Urban fabric",
      ]
    test_dataloaders_names:
      - same_dist
      - ood
      - austria
      - ireland
    plot_on_val: False
