seed_everything: 0
trainer:
  accelerator: auto
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: EarlyStopping
      init_args:
        monitor: val/loss
        patience: 15

  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 1
  enable_checkpointing: true
  default_root_dir: <path>

data: ../../../datamodules/m_cashew_plantation/clay_gw_clay_bands.yaml

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: clay_v1_base
      backbone_pretrained: true
      backbone_img_size: 256
      peft_config:
        method: LORA
        replace_qkv: to_qkv # As we want to apply LoRA separately and only to Q and V, we need to separate the matrix.
        peft_config_kwargs:
          target_modules:
            - to_qkv.q_linear
            - to_qkv.v_linear
            - 1.net.1
            - 1.net.3
          lora_alpha: 16
          r: 16
      necks:
        - name: SelectIndices
          indices: [-1]
        - name: ReshapeTokensToImage
      decoder: LinearDecoder
      decoder_upsampling_size: 8
      rescale: false
      num_classes: 7
    loss: ce
    ignore_index: -1
    freeze_backbone: false
    optimizer: AdamW
    lr: 0.0009575033172114428
    scheduler: ReduceLROnPlateau
    scheduler_hparams:
      patience: 4
      factor: 0.5
    plot_on_val: False
