class_path: peft_geofm.datamodules.MSACropTypeDataModule
init_args:
  batch_size: 8
  num_workers: 8
  data_root: <geobench_datasets_path>
  use_metadata: clay_tlgw
  partition: default
  bands: ["BLUE", "GREEN", "RED", "NIR_NARROW", "SWIR_1", "SWIR_2"]
  train_transform:
    - class_path: albumentations.D4
    - class_path: albumentations.pytorch.ToTensorV2
